
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.MouseEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Entrar
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Author = new javax.swing.JLabel();
        Layers = new javax.swing.JLayeredPane();
        Panel1 = new javax.swing.JPanel();
        Panel2 = new javax.swing.JPanel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Demo de arrastre/Dragging");
        setResizable(false);

        Author.setText("Hecho por Zabai Armas Herrera");

        Layers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        Layers.setMaximumSize(new java.awt.Dimension(350, 360));
        Layers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel1.setBackground(new java.awt.Color(102, 0, 0));
        Panel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Panel1MouseDragged(evt);
            }
        });
        Panel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Panel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Panel1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Layers.add(Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        Panel2.setBackground(new java.awt.Color(51, 153, 0));
        Panel2.setPreferredSize(new java.awt.Dimension(200, 200));
        Panel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Panel2MouseDragged(evt);
            }
        });
        Panel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Panel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Panel2MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        Layers.add(Panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Scotland.jpg"))); // NOI18N
        Layers.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Layers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Author))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Layers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Author)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Panel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel1MousePressed
        // TODO add your handling code here:
        // Obtiene las dimensiones actuales del contenedor y del objeto
        // Se actualiza por si existe resize
        Rectangle r = Layers.getBounds();
        wBox = r.width;
        hBox = r.height;
        r = Panel1.getBounds();
        wPanel1 = r.width;
        hPanel1 = r.height;
        
        // Obtiene la posición actual del panel
        x0Panel1 = r.x;
        y0Panel1 = r.y;
        
        // Obtiene la posición actual del ratón
        Point p = Layers.getMousePosition();
        x0Mouse = p.x;
        y0Mouse = p.y;
        
        Panel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_Panel1MousePressed

    private void Panel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel1MouseDragged
        // TODO add your handling code here:
        // Obtener la posición actual del ratón
        Point p = Layers.getMousePosition();
        if(p == null) return;
        
        // Calcular la nueva posición del panel
        int xPanel1 = x0Panel1 + p.x-x0Mouse;
        int yPanel1 = y0Panel1 + p.y-y0Mouse;
        
        // Evita que salga del área de trabajo
        if(xPanel1 < 0) xPanel1 = 0;
        if(yPanel1 < 0) yPanel1 = 0;
        
        int xMax = wBox - wPanel1;
        int yMax = hBox - hPanel1;
        if(xPanel1 > xMax) xPanel1 = xMax;
        if(yPanel1 > yMax) yPanel1 = yMax;
        
        // Actualiza la posición del panel
        p.x = xPanel1;
        p.y = yPanel1;
        Panel1.setLocation(p);
    }//GEN-LAST:event_Panel1MouseDragged

    private void Panel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel1MouseReleased
        // TODO add your handling code here:
        Panel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_Panel1MouseReleased

    private void Panel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel2MouseClicked
        // TODO add your handling code here:
        int button = evt.getButton();
        if(button == MouseEvent.BUTTON1) Layers.moveToFront(Panel2);
        
        if(button == MouseEvent.BUTTON3) Layers.moveToFront(Panel1);
    }//GEN-LAST:event_Panel2MouseClicked

    private void Panel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel2MousePressed
        // TODO add your handling code here:
        Rectangle r = Layers.getBounds();
        wBox = r.width;
        hBox = r.height;
        r = Panel2.getBounds();
        wPanel2 = r.width;
        hPanel2 = r.height;
        
        // Obtiene la posición actual del panel
        x0Panel2 = r.x;
        y0Panel2 = r.y;
        
        // Obtiene la posición actual del ratón
        Point p = Layers.getMousePosition();
        x0Mouse = p.x;
        y0Mouse = p.y;
        
        Panel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_Panel2MousePressed

    private void Panel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel2MouseDragged
        // TODO add your handling code here:
        // Obtener la posición actual del ratón
        Point p = Layers.getMousePosition();
        if(p == null) return;
        
        // Calcular la nueva posición del panel
        int xPanel2 = x0Panel2 + p.x-x0Mouse;
        int yPanel2 = y0Panel2 + p.y-y0Mouse;
        
        // Evita que salga del área de trabajo
        if(xPanel2 < 0) xPanel2 = 0;
        if(yPanel2 < 0) yPanel2 = 0;
        
        int xMax = wBox - wPanel2;
        int yMax = hBox - hPanel2;
        if(xPanel2 > xMax) xPanel2 = xMax;
        if(yPanel2 > yMax) yPanel2 = yMax;
        
        // Actualiza la posición del panel
        p.x = xPanel2;
        p.y = yPanel2;
        Panel2.setLocation(p);
    }//GEN-LAST:event_Panel2MouseDragged

    private void Panel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel2MouseReleased
        // TODO add your handling code here:
        Panel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_Panel2MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Author;
    private javax.swing.JLabel BG;
    private javax.swing.JLayeredPane Layers;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    // End of variables declaration//GEN-END:variables
    // Variables de intercambio de informacion entre eventos
    // Dimensiones del espacio y de la primera capa
    private int wBox, hBox, wPanel1, hPanel1, wPanel2, hPanel2;
    
    private int x0Panel1, y0Panel1, x0Panel2, y0Panel2, x0Mouse, y0Mouse;
}
