
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Vector;
import javax.swing.ListSelectionModel;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrador
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        
        ButtonGroup.add(TButtonSimple);
        ButtonGroup.add(TButtonSimpleRange);
        ButtonGroup.add(TButtonMultRange);
        TButtonMultRange.setSelected(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonGroup = new javax.swing.ButtonGroup();
        Author = new javax.swing.JLabel();
        PanelData = new javax.swing.JPanel();
        TextData = new javax.swing.JTextField();
        ButtonToList1 = new javax.swing.JButton();
        PanelList1 = new javax.swing.JPanel();
        ScrollList1 = new javax.swing.JScrollPane();
        List1 = new javax.swing.JList<>();
        ButtonResetSelectionList1 = new javax.swing.JButton();
        PanelSelectionMode = new javax.swing.JPanel();
        TButtonSimple = new javax.swing.JToggleButton();
        TButtonSimpleRange = new javax.swing.JToggleButton();
        TButtonMultRange = new javax.swing.JToggleButton();
        PanelList2 = new javax.swing.JPanel();
        ScrollList2 = new javax.swing.JScrollPane();
        List2 = new javax.swing.JList<>();
        ButtonResetList2 = new javax.swing.JButton();
        ButtonDeleteSelectionList2 = new javax.swing.JButton();
        ButtonSortList2 = new javax.swing.JButton();
        ButtonToList2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Listas y Botones");
        setPreferredSize(new java.awt.Dimension(825, 512));
        setResizable(false);

        Author.setText("Hecho por Zabai Armas Herrera");

        PanelData.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        PanelData.setPreferredSize(new java.awt.Dimension(128, 64));

        javax.swing.GroupLayout PanelDataLayout = new javax.swing.GroupLayout(PanelData);
        PanelData.setLayout(PanelDataLayout);
        PanelDataLayout.setHorizontalGroup(
            PanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextData)
        );
        PanelDataLayout.setVerticalGroup(
            PanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        ButtonToList1.setText("A Lista 1 ->");
        ButtonToList1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonToList1ActionPerformed(evt);
            }
        });

        PanelList1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista 1", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        PanelList1.setPreferredSize(new java.awt.Dimension(256, 0));

        ScrollList1.setViewportView(List1);

        ButtonResetSelectionList1.setText("Reiniciar selección");
        ButtonResetSelectionList1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResetSelectionList1ActionPerformed(evt);
            }
        });

        PanelSelectionMode.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modo de selección", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        TButtonSimple.setText("Simple");
        TButtonSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TButtonSimpleActionPerformed(evt);
            }
        });

        TButtonSimpleRange.setText("Intervalo Simple");
        TButtonSimpleRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TButtonSimpleRangeActionPerformed(evt);
            }
        });

        TButtonMultRange.setText("Intervalo Múltiple");
        TButtonMultRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TButtonMultRangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSelectionModeLayout = new javax.swing.GroupLayout(PanelSelectionMode);
        PanelSelectionMode.setLayout(PanelSelectionModeLayout);
        PanelSelectionModeLayout.setHorizontalGroup(
            PanelSelectionModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSelectionModeLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(PanelSelectionModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TButtonMultRange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TButtonSimple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TButtonSimpleRange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelSelectionModeLayout.setVerticalGroup(
            PanelSelectionModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSelectionModeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TButtonSimple)
                .addGap(18, 18, 18)
                .addComponent(TButtonSimpleRange)
                .addGap(18, 18, 18)
                .addComponent(TButtonMultRange)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelList1Layout = new javax.swing.GroupLayout(PanelList1);
        PanelList1.setLayout(PanelList1Layout);
        PanelList1Layout.setHorizontalGroup(
            PanelList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelList1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelList1Layout.createSequentialGroup()
                        .addComponent(PanelSelectionMode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelList1Layout.createSequentialGroup()
                        .addGroup(PanelList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ScrollList1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelList1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(ButtonResetSelectionList1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PanelList1Layout.setVerticalGroup(
            PanelList1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelList1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollList1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonResetSelectionList1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelSelectionMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanelList2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista 2", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        PanelList2.setPreferredSize(new java.awt.Dimension(256, 0));

        ScrollList2.setViewportView(List2);

        ButtonResetList2.setText("Reiniciar lista");
        ButtonResetList2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResetList2ActionPerformed(evt);
            }
        });

        ButtonDeleteSelectionList2.setText("Borrar selección");
        ButtonDeleteSelectionList2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteSelectionList2ActionPerformed(evt);
            }
        });

        ButtonSortList2.setText("Ordena la lista");
        ButtonSortList2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSortList2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelList2Layout = new javax.swing.GroupLayout(PanelList2);
        PanelList2.setLayout(PanelList2Layout);
        PanelList2Layout.setHorizontalGroup(
            PanelList2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelList2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelList2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(ButtonResetList2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonDeleteSelectionList2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonSortList2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ScrollList2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelList2Layout.setVerticalGroup(
            PanelList2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelList2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollList2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonResetList2)
                .addGap(18, 18, 18)
                .addComponent(ButtonDeleteSelectionList2)
                .addGap(18, 18, 18)
                .addComponent(ButtonSortList2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ButtonToList2.setText("A Lista2 ->");
        ButtonToList2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonToList2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(ButtonToList1)
                    .addComponent(PanelData, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(PanelList1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonToList2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelList2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Author, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(635, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelList2, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                    .addComponent(PanelList1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(PanelData, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonToList1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 371, Short.MAX_VALUE)
                        .addComponent(Author)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(ButtonToList2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonToList1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonToList1ActionPerformed
        // TODO add your handling code here:
        String data = TextData.getText();
        if(data == null || data.isEmpty()) return;
        TextData.setText("");
        
        if(List1.getModel().getSize() == 0){
            String[] values = new String[1];
            values[0] = data;
            List1.setListData(values);
        }else{
            List1.setSelectionInterval(0, List1.getModel().getSize()-1);
            List values = List1.getSelectedValuesList();
            values.add(data);
            List1.setListData((String[]) values.toArray(new String[0]));
        }
    }//GEN-LAST:event_ButtonToList1ActionPerformed

    private void TButtonSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TButtonSimpleActionPerformed
        // TODO add your handling code here:
        List1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }//GEN-LAST:event_TButtonSimpleActionPerformed

    private void TButtonSimpleRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TButtonSimpleRangeActionPerformed
        // TODO add your handling code here:
        List1.setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);
    }//GEN-LAST:event_TButtonSimpleRangeActionPerformed

    private void TButtonMultRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TButtonMultRangeActionPerformed
        // TODO add your handling code here:
        List1.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
    }//GEN-LAST:event_TButtonMultRangeActionPerformed

    private void ButtonResetSelectionList1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResetSelectionList1ActionPerformed
        // TODO add your handling code here:
        try{
            List1.setSelectedIndices(null);
        }catch(NullPointerException e){
        }
    }//GEN-LAST:event_ButtonResetSelectionList1ActionPerformed

    private void ButtonToList2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonToList2ActionPerformed
        // TODO add your handling code here:
        List selected = List1.getSelectedValuesList();
        List2.setListData((String[]) selected.toArray(new String[0]));
    }//GEN-LAST:event_ButtonToList2ActionPerformed

    private void ButtonResetList2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResetList2ActionPerformed
        // TODO add your handling code here:
        List selected = List2.getSelectedValuesList();
        selected.clear();
        List2.setListData((String[]) selected.toArray(new String[0]));
    }//GEN-LAST:event_ButtonResetList2ActionPerformed

    private void ButtonDeleteSelectionList2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteSelectionList2ActionPerformed
        // TODO add your handling code here:
        List selected = List2.getSelectedValuesList();
        if(selected.isEmpty()) return;
        
        List2.setSelectionInterval(0, List2.getModel().getSize()-1);
        List totalList = List2.getSelectedValuesList();
        totalList.removeAll(selected);
        List2.setListData((String[]) totalList.toArray(new String[0]));
    }//GEN-LAST:event_ButtonDeleteSelectionList2ActionPerformed

    private void ButtonSortList2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSortList2ActionPerformed
        // TODO add your handling code here:
        List2.setSelectionInterval(0, List2.getModel().getSize()-1);
        List totalList = List2.getSelectedValuesList();
        Collections.sort(totalList);
        List2.setListData((String[]) totalList.toArray(new String[0]));
    }//GEN-LAST:event_ButtonSortList2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Author;
    private javax.swing.JButton ButtonDeleteSelectionList2;
    private javax.swing.ButtonGroup ButtonGroup;
    private javax.swing.JButton ButtonResetList2;
    private javax.swing.JButton ButtonResetSelectionList1;
    private javax.swing.JButton ButtonSortList2;
    private javax.swing.JButton ButtonToList1;
    private javax.swing.JButton ButtonToList2;
    private javax.swing.JList<String> List1;
    private javax.swing.JList<String> List2;
    private javax.swing.JPanel PanelData;
    private javax.swing.JPanel PanelList1;
    private javax.swing.JPanel PanelList2;
    private javax.swing.JPanel PanelSelectionMode;
    private javax.swing.JScrollPane ScrollList1;
    private javax.swing.JScrollPane ScrollList2;
    private javax.swing.JToggleButton TButtonMultRange;
    private javax.swing.JToggleButton TButtonSimple;
    private javax.swing.JToggleButton TButtonSimpleRange;
    private javax.swing.JTextField TextData;
    // End of variables declaration//GEN-END:variables
}
