
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Entrar
 */
public class NewJFrame extends javax.swing.JFrame {
    private String password;
    private int tries = 0;
    
    private boolean registered = false;
    private boolean logged = false;

    public NewJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        
        ButtonLogIn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogLogIn = new javax.swing.JDialog();
        InfoLogInPassword = new javax.swing.JLabel();
        TextLogInPassword = new javax.swing.JTextField();
        ButtonLogInOK = new javax.swing.JButton();
        ButtonLoginInCancel = new javax.swing.JButton();
        DialogRegister = new javax.swing.JDialog();
        InfoNewPassword1 = new javax.swing.JLabel();
        TextNewPassword1 = new javax.swing.JTextField();
        InfoNewPassword2 = new javax.swing.JLabel();
        TextNewPassword2 = new javax.swing.JTextField();
        ButtonRegisterOK = new javax.swing.JButton();
        ButtonRegisterCancel = new javax.swing.JButton();
        DialogChangePassword = new javax.swing.JDialog();
        InfoChangePassword1 = new javax.swing.JLabel();
        InfoChangePassword2 = new javax.swing.JLabel();
        TextChangePassword1 = new javax.swing.JTextField();
        TextChangePassword2 = new javax.swing.JTextField();
        ButtonChangeOK = new javax.swing.JButton();
        ButtonChangeCancel = new javax.swing.JButton();
        Author = new javax.swing.JLabel();
        PanelActions = new javax.swing.JPanel();
        ButtonLogIn = new javax.swing.JButton();
        ButtonRegister = new javax.swing.JButton();
        ButtonExit = new javax.swing.JButton();
        PanelStatus = new javax.swing.JPanel();
        InfoRegistered = new javax.swing.JLabel();
        InfoLogged = new javax.swing.JLabel();
        TextRegistered = new javax.swing.JTextField();
        TextLogged = new javax.swing.JTextField();

        DialogLogIn.setTitle("Log In");
        DialogLogIn.setMinimumSize(new java.awt.Dimension(256, 130));
        DialogLogIn.setResizable(false);

        InfoLogInPassword.setText("Contraseña");

        ButtonLogInOK.setText("Aceptar");
        ButtonLogInOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogInOKActionPerformed(evt);
            }
        });

        ButtonLoginInCancel.setText("Cancelar");
        ButtonLoginInCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLoginInCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DialogLogInLayout = new javax.swing.GroupLayout(DialogLogIn.getContentPane());
        DialogLogIn.getContentPane().setLayout(DialogLogInLayout);
        DialogLogInLayout.setHorizontalGroup(
            DialogLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogLogInLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InfoLogInPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextLogInPassword)
                .addContainerGap())
            .addGroup(DialogLogInLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(ButtonLogInOK)
                .addGap(18, 18, 18)
                .addComponent(ButtonLoginInCancel)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        DialogLogInLayout.setVerticalGroup(
            DialogLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogLogInLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(DialogLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InfoLogInPassword)
                    .addComponent(TextLogInPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(DialogLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonLogInOK)
                    .addComponent(ButtonLoginInCancel))
                .addContainerGap())
        );

        DialogRegister.setTitle("Registrarse");
        DialogRegister.setMinimumSize(new java.awt.Dimension(256, 180));
        DialogRegister.setPreferredSize(new java.awt.Dimension(256, 128));
        DialogRegister.setResizable(false);

        InfoNewPassword1.setText("Nueva contraseña");

        InfoNewPassword2.setText("Repetir contraseña");

        ButtonRegisterOK.setText("Aceptar");
        ButtonRegisterOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegisterOKActionPerformed(evt);
            }
        });

        ButtonRegisterCancel.setText("Cancelar");
        ButtonRegisterCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegisterCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DialogRegisterLayout = new javax.swing.GroupLayout(DialogRegister.getContentPane());
        DialogRegister.getContentPane().setLayout(DialogRegisterLayout);
        DialogRegisterLayout.setHorizontalGroup(
            DialogRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DialogRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(InfoNewPassword2)
                    .addComponent(InfoNewPassword1))
                .addGap(18, 18, 18)
                .addGroup(DialogRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextNewPassword1)
                    .addComponent(TextNewPassword2))
                .addContainerGap())
            .addGroup(DialogRegisterLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(ButtonRegisterOK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonRegisterCancel)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        DialogRegisterLayout.setVerticalGroup(
            DialogRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogRegisterLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(DialogRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InfoNewPassword1)
                    .addComponent(TextNewPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DialogRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InfoNewPassword2)
                    .addComponent(TextNewPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(DialogRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonRegisterOK)
                    .addComponent(ButtonRegisterCancel))
                .addContainerGap())
        );

        DialogChangePassword.setTitle("Cambio de contraseña");
        DialogChangePassword.setMinimumSize(new java.awt.Dimension(256, 180));

        InfoChangePassword1.setText("Contraseña actual");

        InfoChangePassword2.setText("Contraseña nueva");

        ButtonChangeOK.setText("OK");
        ButtonChangeOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonChangeOKActionPerformed(evt);
            }
        });

        ButtonChangeCancel.setText("Cancelar");
        ButtonChangeCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonChangeCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DialogChangePasswordLayout = new javax.swing.GroupLayout(DialogChangePassword.getContentPane());
        DialogChangePassword.getContentPane().setLayout(DialogChangePasswordLayout);
        DialogChangePasswordLayout.setHorizontalGroup(
            DialogChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogChangePasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DialogChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DialogChangePasswordLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(ButtonChangeOK, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonChangeCancel)
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DialogChangePasswordLayout.createSequentialGroup()
                        .addGroup(DialogChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InfoChangePassword1)
                            .addComponent(InfoChangePassword2))
                        .addGap(18, 18, 18)
                        .addGroup(DialogChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextChangePassword2)
                            .addComponent(TextChangePassword1))))
                .addContainerGap())
        );
        DialogChangePasswordLayout.setVerticalGroup(
            DialogChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogChangePasswordLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(DialogChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InfoChangePassword1)
                    .addComponent(TextChangePassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DialogChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InfoChangePassword2)
                    .addComponent(TextChangePassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(DialogChangePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonChangeOK)
                    .addComponent(ButtonChangeCancel))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Dialogos Demo");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Author.setText("Hecho por Zabai Armas Herrera");

        PanelActions.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acciones", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        ButtonLogIn.setText("Iniciar sesión");
        ButtonLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogInActionPerformed(evt);
            }
        });

        ButtonRegister.setText("Registrarse");
        ButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegisterActionPerformed(evt);
            }
        });

        ButtonExit.setText("Salir");
        ButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelActionsLayout = new javax.swing.GroupLayout(PanelActions);
        PanelActions.setLayout(PanelActionsLayout);
        PanelActionsLayout.setHorizontalGroup(
            PanelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelActionsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(PanelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(ButtonExit)
                    .addComponent(ButtonRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        PanelActionsLayout.setVerticalGroup(
            PanelActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelActionsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(ButtonLogIn)
                .addGap(11, 11, 11)
                .addComponent(ButtonRegister)
                .addGap(11, 11, 11)
                .addComponent(ButtonExit)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        PanelStatus.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estado", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        InfoRegistered.setText("Registrado");

        InfoLogged.setText("Log In");

        TextRegistered.setEditable(false);
        TextRegistered.setText("No");

        TextLogged.setEditable(false);
        TextLogged.setText("No");

        javax.swing.GroupLayout PanelStatusLayout = new javax.swing.GroupLayout(PanelStatus);
        PanelStatus.setLayout(PanelStatusLayout);
        PanelStatusLayout.setHorizontalGroup(
            PanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(InfoLogged)
                    .addComponent(InfoRegistered))
                .addGap(18, 18, 18)
                .addGroup(PanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextRegistered, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(TextLogged))
                .addContainerGap())
        );
        PanelStatusLayout.setVerticalGroup(
            PanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelStatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InfoRegistered)
                    .addComponent(TextRegistered, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelStatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InfoLogged)
                    .addComponent(TextLogged, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Author)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PanelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelActions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(Author)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogInActionPerformed
        // TODO add your handling code here:
        if(logged){
            int returned = JOptionPane.showConfirmDialog(null,
                    "¿Quiere cerrar sesión?",
                    "Cerrar sesión", 
                    JOptionPane.YES_NO_OPTION);
            if(returned == 0){
                logged = false;
                
                ButtonLogIn.setText("Iniciar sesión");
                TextLogged.setText("No");
                
                ButtonRegister.setEnabled(false);
                ButtonRegister.setText("Registrarse");
            }
        }else{
            DialogLogIn.setLocationRelativeTo(null);
            DialogLogIn.setVisible(true);
        }
    }//GEN-LAST:event_ButtonLogInActionPerformed

                                            
    private void ButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExitActionPerformed
        // TODO add your handling code here:
        int returned = JOptionPane.showConfirmDialog(null, 
                "¿Realmente quiere salir?",
                "Salir", JOptionPane.YES_NO_OPTION);
        if(returned == 0) System.exit(0);
    }//GEN-LAST:event_ButtonExitActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int returned = JOptionPane.showConfirmDialog(null, 
                "¿Realmente quiere salir?",
                "Salir", JOptionPane.YES_NO_OPTION);
        if(returned == 0) System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void ButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegisterActionPerformed
        // TODO add your handling code here:
        if(!registered){
            DialogRegister.setLocationRelativeTo(null);
            DialogRegister.setVisible(true);
        }else{
            DialogChangePassword.setLocationRelativeTo(null);
            DialogChangePassword.setVisible(true);
        }
    }//GEN-LAST:event_ButtonRegisterActionPerformed

    private void ButtonRegisterCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegisterCancelActionPerformed
        // TODO add your handling code here:
        DialogRegister.setVisible(false);
    }//GEN-LAST:event_ButtonRegisterCancelActionPerformed

    private void ButtonRegisterOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegisterOKActionPerformed
        // TODO add your handling code here:
        password = String.valueOf(TextNewPassword1.getText());
        String check = String.valueOf(TextNewPassword2.getText());
        
        TextNewPassword1.setText(null);
        TextNewPassword2.setText(null);
        
        if(password.equals(check)){
            registered = true;
            
            TextRegistered.setText("Sí");
            
            DialogRegister.setVisible(false);
            
            ButtonRegister.setEnabled(false);
            ButtonLogIn.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(null,
                    "Las contraseñas son diferentes\nIntentalo de nuevo",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButtonRegisterOKActionPerformed

    private void ButtonLoginInCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLoginInCancelActionPerformed
        // TODO add your handling code here:
        DialogLogIn.setVisible(false);
    }//GEN-LAST:event_ButtonLoginInCancelActionPerformed

    private void ButtonLogInOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogInOKActionPerformed
        // TODO add your handling code here:
        String check = String.valueOf(TextLogInPassword.getText());
        
        TextLogInPassword.setText(null);
        
        if(tries == 3){
            JOptionPane.showMessageDialog(null,
                    "Has llegado al nº máximo de intentos",
                    "Salir", JOptionPane.OK_OPTION);
            System.exit(1);
        }
        if(check.equals(password)){
            logged = true;
            tries = 0;
            
            TextLogged.setText("Sí");
            
            DialogLogIn.setVisible(false);
            
            ButtonLogIn.setText("Cerrar sesión");
            
            ButtonRegister.setEnabled(true);
            ButtonRegister.setText("Cambiar contraseña");
        }else{
            JOptionPane.showMessageDialog(null,
                    "Contraseña incorrecta\nIntentalo de nuevo", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            tries++;
        }
    }//GEN-LAST:event_ButtonLogInOKActionPerformed

    private void ButtonChangeOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonChangeOKActionPerformed
        // TODO add your handling code here:
        String actualPass = TextChangePassword1.getText();
        String newPass = TextChangePassword2.getText();
        
        TextChangePassword1.setText(null);
        TextChangePassword2.setText(null);
        
        if(actualPass.equals(password)){
            password = newPass;
            DialogChangePassword.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null,
                    "La contraseña actual introducida no es correcta",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButtonChangeOKActionPerformed

    private void ButtonChangeCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonChangeCancelActionPerformed
        // TODO add your handling code here:
        DialogChangePassword.setVisible(false);
    }//GEN-LAST:event_ButtonChangeCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Author;
    private javax.swing.JButton ButtonChangeCancel;
    private javax.swing.JButton ButtonChangeOK;
    private javax.swing.JButton ButtonExit;
    private javax.swing.JButton ButtonLogIn;
    private javax.swing.JButton ButtonLogInOK;
    private javax.swing.JButton ButtonLoginInCancel;
    private javax.swing.JButton ButtonRegister;
    private javax.swing.JButton ButtonRegisterCancel;
    private javax.swing.JButton ButtonRegisterOK;
    private javax.swing.JDialog DialogChangePassword;
    private javax.swing.JDialog DialogLogIn;
    private javax.swing.JDialog DialogRegister;
    private javax.swing.JLabel InfoChangePassword1;
    private javax.swing.JLabel InfoChangePassword2;
    private javax.swing.JLabel InfoLogInPassword;
    private javax.swing.JLabel InfoLogged;
    private javax.swing.JLabel InfoNewPassword1;
    private javax.swing.JLabel InfoNewPassword2;
    private javax.swing.JLabel InfoRegistered;
    private javax.swing.JPanel PanelActions;
    private javax.swing.JPanel PanelStatus;
    private javax.swing.JTextField TextChangePassword1;
    private javax.swing.JTextField TextChangePassword2;
    private javax.swing.JTextField TextLogInPassword;
    private javax.swing.JTextField TextLogged;
    private javax.swing.JTextField TextNewPassword1;
    private javax.swing.JTextField TextNewPassword2;
    private javax.swing.JTextField TextRegistered;
    // End of variables declaration//GEN-END:variables
}
