
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Entrar
 */
public class RGBSlider extends javax.swing.JFrame {

    /**
     * Creates new form RGBSlider
     */
    public RGBSlider() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        red = 255/2;
        green = 255/2;
        blue = 255/2;
        
        updateComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RSlider = new javax.swing.JSlider();
        GSlider = new javax.swing.JSlider();
        BSlider = new javax.swing.JSlider();
        RValue = new javax.swing.JTextField();
        GValue = new javax.swing.JTextField();
        BValue = new javax.swing.JTextField();
        RInfo = new javax.swing.JLabel();
        GInfo = new javax.swing.JLabel();
        BInfo = new javax.swing.JLabel();
        Button = new javax.swing.JButton();
        HexInfo = new javax.swing.JLabel();
        HexValue = new javax.swing.JTextField();

        setTitle("Deslizador RGB");

        RSlider.setMajorTickSpacing(50);
        RSlider.setMaximum(255);
        RSlider.setPaintLabels(true);
        RSlider.setPaintTicks(true);
        RSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RSliderStateChanged(evt);
            }
        });
        RSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RSliderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RSliderMouseExited(evt);
            }
        });

        GSlider.setMajorTickSpacing(50);
        GSlider.setMaximum(255);
        GSlider.setPaintLabels(true);
        GSlider.setPaintTicks(true);
        GSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                GSliderStateChanged(evt);
            }
        });
        GSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GSliderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GSliderMouseExited(evt);
            }
        });

        BSlider.setMajorTickSpacing(50);
        BSlider.setMaximum(255);
        BSlider.setPaintLabels(true);
        BSlider.setPaintTicks(true);
        BSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BSliderStateChanged(evt);
            }
        });
        BSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BSliderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BSliderMouseExited(evt);
            }
        });

        RValue.setText("---");
        RValue.setMinimumSize(new java.awt.Dimension(6, 59));
        RValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RValueActionPerformed(evt);
            }
        });

        GValue.setText("---");
        GValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GValueActionPerformed(evt);
            }
        });

        BValue.setText("---");
        BValue.setName(""); // NOI18N
        BValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BValueActionPerformed(evt);
            }
        });

        RInfo.setText("Red");

        GInfo.setText("Green");

        BInfo.setText("Blue");

        Button.setText("- - -");

        HexInfo.setText("Hex");

        HexValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HexValueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(HexInfo)
                    .addComponent(BInfo)
                    .addComponent(GInfo)
                    .addComponent(RInfo))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(BSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(BValue, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GValue, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RValue, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(HexValue, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Button, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(RInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(GInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(BInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HexInfo)
                            .addComponent(HexValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(89, Short.MAX_VALUE))
                    .addComponent(Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RValueActionPerformed
        // TODO add your handling code here:
        red = Integer.parseInt(RValue.getText());
        updateComponents();
    }//GEN-LAST:event_RValueActionPerformed

    private void GValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GValueActionPerformed
        // TODO add your handling code here:
        green = Integer.parseInt(GValue.getText());
        updateComponents();
    }//GEN-LAST:event_GValueActionPerformed

    private void BValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BValueActionPerformed
        // TODO add your handling code here:
        blue = Integer.parseInt(BValue.getText());
        updateComponents();
    }//GEN-LAST:event_BValueActionPerformed

    private void RSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RSliderStateChanged
        // TODO add your handling code here:
        red = RSlider.getValue();
        updateComponents();
    }//GEN-LAST:event_RSliderStateChanged

    private void GSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_GSliderStateChanged
        // TODO add your handling code here:
        green = GSlider.getValue();
        updateComponents();
    }//GEN-LAST:event_GSliderStateChanged

    private void BSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BSliderStateChanged
        // TODO add your handling code here:
        blue = BSlider.getValue();
        updateComponents();
    }//GEN-LAST:event_BSliderStateChanged

    private void HexValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HexValueActionPerformed
        // TODO add your handling code here:
        String hex = HexValue.getText();
        
        red = Integer.valueOf(hex.substring(1, 3), 16);
        green = Integer.valueOf(hex.substring(3, 5), 16);
        blue = Integer.valueOf(hex.substring(5, 7), 16);
        
        updateComponents();
    }//GEN-LAST:event_HexValueActionPerformed

    private void RSliderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RSliderMouseEntered
        // TODO add your handling code here:
        Button.setForeground(Color.RED);
        Button.setText("Dentro");
    }//GEN-LAST:event_RSliderMouseEntered

    private void GSliderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GSliderMouseEntered
        // TODO add your handling code here:
        Button.setForeground(Color.GREEN);
        Button.setText("Dentro");
    }//GEN-LAST:event_GSliderMouseEntered

    private void BSliderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BSliderMouseEntered
        // TODO add your handling code here:
        Button.setForeground(Color.BLUE);
        Button.setText("Dentro");
    }//GEN-LAST:event_BSliderMouseEntered

    private void RSliderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RSliderMouseExited
        // TODO add your handling code here:
        Button.setText("Fuera");
    }//GEN-LAST:event_RSliderMouseExited

    private void GSliderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GSliderMouseExited
        // TODO add your handling code here:
        Button.setText("Fuera");
    }//GEN-LAST:event_GSliderMouseExited

    private void BSliderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BSliderMouseExited
        // TODO add your handling code here:
        Button.setText("Fuera");
    }//GEN-LAST:event_BSliderMouseExited

    
    private void updateComponents(){
        RSlider.setValue(red);
        GSlider.setValue(green);
        BSlider.setValue(blue);
        
        RValue.setText(String.valueOf(red));
        GValue.setText(String.valueOf(green));
        BValue.setText(String.valueOf(blue));
        
        HexValue.setText(String.format("#%02x%02x%02x", red, green, blue));
        
        Button.setBackground(new Color(red, green, blue));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BInfo;
    private javax.swing.JSlider BSlider;
    private javax.swing.JTextField BValue;
    private javax.swing.JButton Button;
    private javax.swing.JLabel GInfo;
    private javax.swing.JSlider GSlider;
    private javax.swing.JTextField GValue;
    private javax.swing.JLabel HexInfo;
    private javax.swing.JTextField HexValue;
    private javax.swing.JLabel RInfo;
    private javax.swing.JSlider RSlider;
    private javax.swing.JTextField RValue;
    // End of variables declaration//GEN-END:variables
    private int red, green, blue;
}